### ISSUE TITLE
Collection Types - Filters (500 internal error)

### ISSUE THREAD

**Issue by rrubio** [arrowheadapps/strapi-connector-firestore#48]
When performing a filter under "Collection Types" i get an internal error. Under headers i can see the right filter being used. The fields is of type Int:

**Filter**

![image](https://user-images.githubusercontent.com/4221574/107177838-e2b8de80-6a26-11eb-9f67-3b1c60fb31a5.png)

**Header**

`calendar-date?page=1&pageSize=10&_sort=recId:ASC&_where[0][calendarDay]=1`

NOTE: querystring query works fine see examle below:

`api/calendar-date?calendarDay=${calendarDay}`

**HTTP Response** 

![image](https://user-images.githubusercontent.com/4221574/107177584-45f64100-6a26-11eb-9112-249d36928cbb.png)

`
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
`

**Header** 

![image](https://user-images.githubusercontent.com/4221574/107177563-3b3bac00-6a26-11eb-9005-353661ab55ca.png)

**UI Error message**

![image](https://user-images.githubusercontent.com/4221574/107177460-016aa580-6a26-11eb-958f-5804db4b329e.png)

**Comment by brettwillis** [comment]
Hi @rrubio , I'm pretty that this is due to #23. The complex query format with `_where` is not implemented yet, it's next on my list.

To be sure, there should be some Cloud Run error output for this one, could you check at https://console.cloud.google.com/logs?

But like you say, for this simple query, the simple format should still work in the meantime `calendar-date?page=1&pageSize=10&_sort=recId:ASC&calendarDay=1`.

**Comment by rrubio** [comment]
@brettwillis thank you man. I'll need to confirm logs on cloud run.

**Comment by brettwillis** [comment]
@rrubio I've implemented complex queries in version `3.0.0-alpha.28`. Give it a try and please let me know how it goes.

**Comment by rrubio** [comment]
@brettwillis  thank you. I'll be able to check this week and provide you with an update.
