### ISSUE TITLE
Unable to login in local environment

### ISSUE THREAD

**Issue by terumik** [arrowheadapps/strapi-connector-firestore#62]
I'm trying to run examples/cloud-run-and-hosting locally, but stuck on login screen.  Any help would be appreciated.

What I did: 
- Run npm install on root and examples/cloud-run-and-hosting
- Changed the projectId in cloud-run-and-hosting/.firebaserc
- Run firebase init on /cloud-run-and-hosting
- Change the projectId in /cloud-run-and-hosting/config/database.js
- Created /cloud-run-and-hosting/.env
`GCP_PROJECT: my-firebase-project`
`ADMIN_JWT_SECRET=jwt-token (created by running node -e "console.log(require('crypto').randomBytes(64).toString('base64'))" # (all users))`
- Added the jwt token to cloud-run-and-hosting/server.js
- When I launched the emulator locally, port 8080 was taken. I changed the port in firebase.json to 8081. Along with this, change the port of server.js to 8082 => Could not start up with error
- Changed the port under root/index.ts, root/index.js, and root/firestore.js to 8081
- The emulator and Strapi application started up successfully
- When I tried to visit the login page (http://localhost:8082/admin/auth/login), I was redirected. I tried to register with my existing credentials then reload
- Login page appeared. I tried to login => 500 error and could not log in

Am I missing something?
I'm also stuck on deploying the example project to the remote, but I'll try some more and if it doesn't work, I'll ask a separate question later.

Related: https://github.com/arrowheadapps/strapi-connector-firestore/issues/11

**Comment by brettwillis** [comment]
Hi @terumik 
I'll need to give it a run with the change of ports like you are, so I can see how to get it working that way. I'll try in the next few days. In the meantime I have some comments:

> I'm also stuck on deploying the example project to the remote

You'll probably want to replace the `"strapi-connector-firestore": "../../"` local dependency with the actual NPM package `"strapi-connector-firestore": "^3.0.0-alpha.38"`. The parent directory isn't available in the Docker build, which will probably be the problem you're encountering?

> Changed the port under root/index.ts, root/index.js, and root/firestore.js to 8081

Are you referring to this line below? As you can see the port that it tries to find the emulator on is hard coded.

https://github.com/arrowheadapps/strapi-connector-firestore/blob/02c29765ca761f765a580cf4e49dcada737abffe/src/index.ts#L107

Have you considered just trying to find what process is blocking port 8080 instead, so that you can just run the setup normally?

**Comment by brettwillis** [comment]
> I tried to login => 500 error and could not log in

Were there any extra details logged in the console corresponding to this error?

**Comment by brettwillis** [comment]
@terumik no worries, glad it is resolved. Feel free to ask if you have any other issues.
